# Generated by Django 4.0.6 on 2022-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='NameEvent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='NameRoom',
            field=models.CharField(max_length=50),
        ),
    ]
