# Generated by Django 4.0.6 on 2022-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0002_room_address_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='NameRoom',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
